CREATE TABLE transportation (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  transport_date TEXT NOT NULL,--not sure what datatypes to put here, might be timestamp but it should correspond to the time and date the user inputs; so maybe just numbers?
  transport_time TEXT NOT NULL, -- might not need 2 different fields; can be 2 selectors to make one data type
  transport_location TEXT NOT NULL,
  destination TEXT NOT NULL,
  transport_type TEXT NOT NULL,
  transport_number TEXT NOT NULL,
  date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);